airbnb:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: XROWZYV-BS94358
      user: dbt
      role: TRANSFORM
      private_key: |
        -----BEGIN ENCRYPTED PRIVATE KEY-----
        MIIFNTBfBgkqhkiG9w0BBQ0wUjAxBgkqhkiG9w0BBQwwJAQQj283jG92exWzyrXo
        Imh05wICCAAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEKvfEjM+ZNBvpUf5
        69IWfhcEggTQmp4NkKcEIA/hvrChAaiQC2EnauxW3oAedYBy//BG7a/OckhQtbQg
        UKqpF9ekA1oTJ9E0ayYhd+DY+P2a3H7SdFgCfPKxENhp+j6YPUb1GEXB4nhcCoEg
        ipFpSK0lXqX90Vipp6p8pgpKnquIvSTZRlBDd5zDRtGil4fJy5//onxU9t4xSoRo
        MKJdikcBGHTEHZjYRooG/B70QA6mC+pOAw5YFAVfsF5dnu8SzW/l59qkxTx+GA/p
        K44Yl560X0N2M+ZhyYtLfZmDTOb8/OXKYLXIftgog8obvoX8HxI+/i9ee2gVu4zf
        3ifvKKjrx73/cY27g7NZr3NuWu7/qB1/8wlzbT4UIyMtirZWVWJ/+mCQM7FQd1oF
        jNelcFe8t5twvtQgchkAf4Dake8nEHNIUNy5sut1Z87hJAWXbGqtH/t9YSxS33Dq
        WKLeq4ycy7xvGwdtOCm75jdmxmpgl2WJ+MCuBqHYxE+wTNjNbucHnZxnjsr2N/5c
        oO2p2dvtky3Hrsdkmy8sqH2CF+KRq0uctRC0yT5yMkYMhznnL1vTuvXzSvGN74CX
        JuEfF3dj/uqU+QKjPiWnGcoTzVNfkzbs7BYDNSxWp6o6/9FSlnsG+ZFm3yvHKLCM
        PYUA9bRN81R8o1neNdKgwK2vXbWLCTQ8Ggm2MBSX+HnaxyDPEzDLFjqgSFrvcktg
        ORhiJZYHP2EH6G4JThximMVSaiVXJz1sD46176wSyRzdIoGsSba0n8k6ekDufTO2
        w70pAXvUo52pKyOZRjqS8+9QCPkHcwnQgoSwzFQBm+rYnbrpsJ4hVmwfNNoQeBOb
        YvSTZRlBDd5zDRtGil4fJy5//onxU9t4xSoRoMKJdikcBGHTEHZjYRooG/B70QA6m
        C+pOAw5YFAVfsF5dnu8SzW/l59qkxTx+GA/pK44Yl560X0N2M+ZhyYtLfZmDTOb8
        /OXKYLXIftgog8obvoX8HxI+/i9ee2gVu4zf3ifvKKjrx73/cY27g7NZr3NuWu7/
        qB1/8wlzbT4UIyMtirZWVWJ/+mCQM7FQd1oFjNelcFe8t5twvtQgchkAf4Dake8n
        EHNIUNy5sut1Z87hJAWXbGqtH/t9YSxS33DqWKLeq4ycy7xvGwdtOCm75jdmxmpg
        l2WJ+MCuBqHYxE+wTNjNbucHnZxnjsr2N/5coO2p2dvtky3Hrsdkmy8sqH2CF+KR
        q0uctRC0yT5yMkYMhznnL1vTuvXzSvGN74CXJuEfF3dj/uqU+QKjPiWnGcoTzVNf
        kzbs7BYDNSxWp6o6/9FSlnsG+ZFm3yvHKLCMPYUA9bRN81R8o1neNdKgwK2vXbWL
        CTQ8Ggm2MBSX+HnaxyDPEzDLFjqgSFrvcktgORhiJZYHP2EH6G4JThximMVSaiVX
        Jz1sD46176wSyRzdIoGsSba0n8k6ekDufTO2w70pAXvUo52pKyOZRjqS8+9QCPkH
        cwnQgoSwzFQBm+rYnbrpsJ4hVmwfNNoQeBObc/Azw9n1unibGkCfHRGOZ13er+qT
        NqOzB5SaYtI0QoCDOzJeHFckR0/kj5fVD7EePKfLjjo441v0X0aZZuS/ltOyhMVM
        /W7TNC+pkL0tVKi9HqywDWtNQ0iJHg0NyNMjb7XWDOj+KLytYaQ7FGi0zLe8e5p6
        5guxrLHUR7dQD16vTLuN+unQvsuPHp/buWAMaizbmdCk/Q2WFWsW3kQwA2JPbutT
        XN63FG/ieT5Lji3xH5Pa1NJbd+V9L5eB0uVDSLxsqL4+w/UMR9/gcfVj6O5VLLb6
        WFUuhxk0E2j44pfTDrMoNcnDbP7XHpX2GzK1zVb65lhupSLy3E5iyMvw7M+uNdcW
        Hyc6rqwMiT5CrYMDRw5t0clncRz640yqSICoBr1fR/3bo2lFe714FMgcHd1O+R9j
        u7PLALiUg/PtQQuvcqGWU20sk027VE38FW0LT89gxMiAw2WH+40lqNlxzhDRVC3H
        SkstUyfoOAipCS3TVmq99aXGF1ZUjS7uUIqfmXcV095vBA/WBdM879IgmxsrdC7r
        qZ55B5/qF83wz1SItD/nU1zPHM9E9xEeSmoHMas4dLCK/0+tof5XPlpLjOET72Ad
        ootTt43dTaEzVv/9Xjqc3ZmYhNXBQ+kA3VAPgo4TPaGzR9HsZpRtrDtDsI7OFgNa
        uy83yUmPCDTT+6ILp5mNG7TAvSK/5jZO7a7UhbDFX6FAITH6iERJmvhxnWeZtQZv
        pIGm8zoNsVLd0jqnV5Cadv+XrXsOls1lleC+EZlYm4cBQphw8OT1hkEbsetDgSgh
        1BOtWfL3KyKSGVAs98KpnMGOmgg=
        -----END ENCRYPTED PRIVATE KEY-----
      private_key_passphrase: q
      database: AIRBNB
      schema: DEV
      threads: 4
      warehouse: COMPUTE_WH

    prod:
      type: snowflake
      account: XROWZYV-BS94358
      user: dbt
      role: TRANSFORM
      private_key: |
        -----BEGIN ENCRYPTED PRIVATE KEY-----
        MIIFNTBfBgkqhkiG9w0BBQ0wUjAxBgkqhkiG9w0BBQwwJAQQj283jG92exWzyrXo
        Imh05wICCAAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEKvfEjM+ZNBvpUf5
        69IWfhcEggTQmp4NkKcEIA/hvrChAaiQC2EnauxW3oAedYBy//BG7a/OckhQtbQg
        UKqpF9ekA1oTJ9E0ayYhd+DY+P2a3H7SdFgCfPKxENhp+j6YPUb1GEXB4nhcCoEg
        ipFpSK0lXqX90Vipp6p8pgpKnquIvSTZRlBDd5zDRtGil4fJy5//onxU9t4xSoRo
        MKJdikcBGHTEHZjYRooG/B70QA6mC+pOAw5YFAVfsF5dnu8SzW/l59qkxTx+GA/p
        K44Yl560X0N2M+ZhyYtLfZmDTOb8/OXKYLXIftgog8obvoX8HxI+/i9ee2gVu4zf
        3ifvKKjrx73/cY27g7NZr3NuWu7/qB1/8wlzbT4UIyMtirZWVWJ/+mCQM7FQd1oF
        jNelcFe8t5twvtQgchkAf4Dake8nEHNIUNy5sut1Z87hJAWXbGqtH/t9YSxS33Dq
        WKLeq4ycy7xvGwdtOCm75jdmxmpgl2WJ+MCuBqHYxE+wTNjNbucHnZxnjsr2N/5c
        oO2p2dvtky3Hrsdkmy8sqH2CF+KRq0uctRC0yT5yMkYMhznnL1vTuvXzSvGN74CX
        JuEfF3dj/uqU+QKjPiWnGcoTzVNfkzbs7BYDNSxWp6o6/9FSlnsG+ZFm3yvHKLCM
        PYUA9bRN81R8o1neNdKgwK2vXbWLCTQ8Ggm2MBSX+HnaxyDPEzDLFjqgSFrvcktg
        ORhiJZYHP2EH6G4JThximMVSaiVXJz1sD46176wSyRzdIoGsSba0n8k6ekDufTO2
        w70pAXvUo52pKyOZRjqS8+9QCPkHcwnQgoSwzFQBm+rYnbrpsJ4hVmwfNNoQeBOb
        YvSTZRlBDd5zDRtGil4fJy5//onxU9t4xSoRoMKJdikcBGHTEHZjYRooG/B70QA6m
        C+pOAw5YFAVfsF5dnu8SzW/l59qkxTx+GA/pK44Yl560X0N2M+ZhyYtLfZmDTOb8
        /OXKYLXIftgog8obvoX8HxI+/i9ee2gVu4zf3ifvKKjrx73/cY27g7NZr3NuWu7/
        qB1/8wlzbT4UIyMtirZWVWJ/+mCQM7FQd1oFjNelcFe8t5twvtQgchkAf4Dake8n
        EHNIUNy5sut1Z87hJAWXbGqtH/t9YSxS33DqWKLeq4ycy7xvGwdtOCm75jdmxmpg
        l2WJ+MCuBqHYxE+wTNjNbucHnZxnjsr2N/5coO2p2dvtky3Hrsdkmy8sqH2CF+KR
        q0uctRC0yT5yMkYMhznnL1vTuvXzSvGN74CXJuEfF3dj/uqU+QKjPiWnGcoTzVNf
        kzbs7BYDNSxWp6o6/9FSlnsG+ZFm3yvHKLCMPYUA9bRN81R8o1neNdKgwK2vXbWL
        CTQ8Ggm2MBSX+HnaxyDPEzDLFjqgSFrvcktgORhiJZYHP2EH6G4JThximMVSaiVX
        Jz1sD46176wSyRzdIoGsSba0n8k6ekDufTO2w70pAXvUo52pKyOZRjqS8+9QCPkH
        cwnQgoSwzFQBm+rYnbrpsJ4hVmwfNNoQeBObc/Azw9n1unibGkCfHRGOZ13er+qT
        NqOzB5SaYtI0QoCDOzJeHFckR0/kj5fVD7EePKfLjjo441v0X0aZZuS/ltOyhMVM
        /W7TNC+pkL0tVKi9HqywDWtNQ0iJHg0NyNMjb7XWDOj+KLytYaQ7FGi0zLe8e5p6
        5guxrLHUR7dQD16vTLuN+unQvsuPHp/buWAMaizbmdCk/Q2WFWsW3kQwA2JPbutT
        XN63FG/ieT5Lji3xH5Pa1NJbd+V9L5eB0uVDSLxsqL4+w/UMR9/gcfVj6O5VLLb6
        WFUuhxk0E2j44pfTDrMoNcnDbP7XHpX2GzK1zVb65lhupSLy3E5iyMvw7M+uNdcW
        Hyc6rqwMiT5CrYMDRw5t0clncRz640yqSICoBr1fR/3bo2lFe714FMgcHd1O+R9j
        u7PLALiUg/PtQQuvcqGWU20sk027VE38FW0LT89gxMiAw2WH+40lqNlxzhDRVC3H
        SkstUyfoOAipCS3TVmq99aXGF1ZUjS7uUIqfmXcV095vBA/WBdM879IgmxsrdC7r
        qZ55B5/qF83wz1SItD/nU1zPHM9E9xEeSmoHMas4dLCK/0+tof5XPlpLjOET72Ad
        ootTt43dTaEzVv/9Xjqc3ZmYhNXBQ+kA3VAPgo4TPaGzR9HsZpRtrDtDsI7OFgNa
        uy83yUmPCDTT+6ILp5mNG7TAvSK/5jZO7a7UhbDFX6FAITH6iERJmvhxnWeZtQZv
        pIGm8zoNsVLd0jqnV5Cadv+XrXsOls1lleC+EZlYm4cBQphw8OT1hkEbsetDgSgh
        1BOtWfL3KyKSGVAs98KpnMGOmgg=
        -----END ENCRYPTED PRIVATE KEY-----
      private_key_passphrase: q
      database: AIRBNB
      schema: PROD
      threads: 4
      warehouse: COMPUTE_WH